### PR TITLE
reduce static gdb python size

### PR DESCRIPTION
**Pull request by guyush1**
The newer submodule will create smaller static python libraries.

### CODE REVIEW

**Comment by guyush1** [comment]
This closes #23

**Comment by guyush1** [comment]
@roddyrap please have a look at this. Also - could you please review the updated deepfrozen.o file, and check if there are more modules we can remove? the binary size is ~32MB still, but reducing it further is always nice :)

**Comment by roddyrap** [comment]
Sure, will try my best.

**Comment by guyush1** [comment]
@roddyrap i have removed the said modules (now gdb size is 31MB). could you have a look and approve both submodule and this pr if everything looks fine to you?

**Comment by guyush1** [comment]
@roddyrap i have removed the said modules (now gdb size is 31MB). could you have a look and approve both submodule and this pr if everything looks fine to you?

**Review by roddyrap — APPROVED** [review]

**Comment by guyush1** [comment]
just FYI: i tried tinkering with the binary in order to make it smaller. the best i got is 28MB, but i had to remove some maybe-needed modules and the compilation time went up by a lot since i used lto (i also tried -O3 but dont get me started on that).

**Pull request merged**
